### ISSUE TITLE
Package some form of "minimal" libarrow?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/arrow-cpp-feedstock#1035]
I just saw that pandas is [considering](https://github.com/pandas-dev/pandas/pull/52711) to hard-depend on pyarrow. This would substantially blow up the footprint of all pandas installs (which is pandas' choice to make), but even more so on conda-forge, because we package more bindings than the wheels[^1].

This is not the first time that this topic has come up, c.f. below:

[^1]: given the difficulty of building arrow, they are effectively uninstallable otherwise, hence the maximalist approach to packaging on this feedstock, resp. in conda-forge in general 

> > @h-vetinari: That said, there's a larger theme here that arrow keeps growing non-trivial dependencies. I guess we could introduce a separate output for a "minimal" arrow (`libarrow-core`?)
>
> @jorisvandenbossche: That's indeed something we have to look at long term, but probably good for a separate issue? (it seems to me that regardless of that, cudatoolkit should never be a dependency for the CPU version?) 
> libarrow itself actually already exists of multiple shared libraries (libarrow, libarrow_dataset, libarrow_flight, etc). So that could be a first way to split it into multiple packages that should be simpler (eg libarrow_flight has some extra dependencies that are not needed for libarrow itself, such as UCX). On the Arrow C++ side itself, we are also working on further splitting the core libarrow in more shared libraries.

_Originally posted by @jorisvandenbossche in https://github.com/conda-forge/arrow-cpp-feedstock/issues/962#issuecomment-1432924187_

**Comment by jakirkham** [comment]
Think other libraries (like UCX) solve this by dynamically linking to shared libraries for each specific component (like UCX's UCT libraries), which in turn `dlopen` the external libraries that need (like `libcuda.so`). If `dlopen`ing the external library fails, that specific component can be treated as disabled or missing (analogous to catching & handling `ImportError`s in Python)

This isn't something that we would be able to do in this feedstock per se, but it is something upstream might be able to do (not sure how much effort it would be) and in turn we could benefit by building with everything enabled and then moving these extra dependencies to `run_constrained` for the minimal package (and then pull in the kitchen sink for the batteries included package)

**Comment by jorisvandenbossche** [comment]
> That would depend on building `pyarrow` with (say) `PYARROW_WITH_GANDIVA=1`, but the code being smart enough to fail gracefully if `libgandiva.so` isn't found at runtime. That's not something that we can realistically do on the feedstock though, this IMO needs to come from upstream in some way.

I assume this will indeed be the easiest option: build pyarrow with everything enabled (and also install all the cython libs), and only control the separate installation of the libarrow_* parts. That should also give the biggest benefit regarding installation size (and dependencies), given that the python libs are typically smaller than its libarrow counterpart). 
(the alternative would be to actually also split pyarrow into multiple, actually separate, python packages like `pyarrow_flight`, `pyarrow_gandiva`, etc. But that's a lot more work / larger refactor on the pyarrow side, and also introduces dependencies on cython APIs between the different packages etc). 

This is already possible right now, and gives an error about the so not being found at runtime. For example, removing libarrow_dataset.so from my conda env and then importing pyarrow's dataset submodule gives:

```
In [1]: import pyarrow.dataset as ds
...
ImportError: libarrow_dataset.so.1300: cannot open shared object file: No such file or directory
```

We should improve this error message on the pyarrow side (for each optional component, we can add a try/except around the import of the compiled module, re-raising an ImportError with a more informative error message about the subcomponent not being enabled / installed). 
(but I would say the error message is maybe also good enough short-term to start to experiment with this on the conda-forge side, since it would be opt-in anyway)

**Comment by h-vetinari** [comment]
Yeah, I think in terms of user-friendliness, we need to provide a better message than: 
```
ImportError: libarrow_dataset.so.1300: cannot open shared object file: No such file or directory
```

I think it would make sense for upstream arrow to define which libraries can be removed while still expecting core functionality to work, which dependencies each remaining artefact has, and provide _some_ error message upon not finding the respective library (which we can then patch here on the feedstock to add messages like "install this additional output to get it"; alternatively, upstream arrow could of course integrate that into their messages directly à la "if you're using conda-forge builds, ...").

**Comment by raulcd** [comment]
@jorisvandenbossche did some work to improve the error messages if certain submodules were not built.
I plan to spend some time working on this, once I can finally ship Arrow 13.0.0.
Currently `libarrow` contains the rest of the components like `libarrow-flight`, `libarrow-gandiva`, etc
Should we create a new `libarrow-core` with only the core to maintain `libarrow` with backwards compatibility or should we move `libarrow` to be the new minimal component?

**Comment by h-vetinari** [comment]
> Should we create a new `libarrow-core` with only the core to maintain `libarrow` with backwards compatibility or should we move `libarrow` to be the new minimal component?

Both are possible. Aside from adding the respective components like `libarrow-{flight,gandiva,...}`, from my POV we can either choose to:
* add `libarrow-core` and leave `libarrow` as the metapackage that brings in everything
* change `libarrow` to mean "only the core" and add `libarrow-all` for "everything"

The former is probably marginally easier from a migration perspective[^1], the latter is perhaps a slightly cleaner long-term setup. I don't have a strong preference either way.

[^1]: though I don't think too many projects would rely on non-core components, and arrow migrations are not more than a handful feedstocks

**Comment by jorisvandenbossche** [comment]
I agree that there might not be too many users that rely on installing `libarrow` and getting everything (it's mostly some other packages here on conda-forge, but that's something that we can control and fix). 
As long as the main `pyarrow` keeps installing everything by default, and we add a separate `pyarrow-core` or `pyarrow-base` or something like that, as changing `pyarrow` would affect a lot more users.

**Comment by raulcd** [comment]
Do we care about consistency on that naming for `libarrow` and `pyarrow`? Otherwise we are going to have:
* `libarrow` --> minimal build
* `libarrow-all` --> contains everything
* `pyarrow-core` --> minimal pyarrow build
* `pyarrow` --> contains everything

**Comment by jorisvandenbossche** [comment]
The question might also be if `libarrow-all` is needed?  
I don't know which packages would use that. For example `python-duckdb` depends on that, but that also already depends on pyarrow (although we should check if the build dependency would be OK with the minimal build of libarrow). Same for nyxus, snowflake-connector-python, turbodbc, pyfitparquet. Another example is https://github.com/conda-forge/river-ingester-feedstock, which I think from a quick look would also be fine with minimal libarrow and libparquet.
