### ISSUE TITLE
Drop `use_local` from migrators

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/arrow-cpp-feedstock#1039]
Noticed a couple migrators here have `use_local`. For example

https://github.com/conda-forge/arrow-cpp-feedstock/blob/43aa227cecaf002d86b9b066164216ec46bd1cbe/.ci_support/migrations/cuda_112_ppc64le_aarch64.yaml#L18

Would it be possible to drop these? Or is there some reason `use_local` is needed?

Asking as this affects pulling in updates from `conda-forge-pinning` if fixes are needed ( like PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4407 )

It's worth noting this could be handled as part of the next update. Just wanted to check first if there was some reason motivating these lines (beyond maybe inclusion of migrator changes a bit earlier)

**Comment by h-vetinari** [comment]
That's a leftover from the time when we forced cross-compilation of PPC despite having CUDA on aarch. I thought I had dropped it for #899, but seems I dropped that change unintentionally.

All the `use_local`s (if any others still exist) are fine to remove

**Comment by jakirkham** [comment]
All good. Just noticed it while testing out some changes ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/1038 )

Cool, there is no rush here (mostly trying to learn context). So this change can happen whenever the next set of changes go in

**Comment by jakirkham** [comment]
Reopening since this change is still needed on the older branches. For example

https://github.com/conda-forge/arrow-cpp-feedstock/blob/6d49c0b77d8765fe2b0227a7211d1a7ece51b1f4/.ci_support/migrations/cuda_112_ppc64le_aarch64.yaml#L18

**Comment by h-vetinari** [comment]
Done in #1040 #1041 #1043 #1044
