### ISSUE TITLE
Activate.sh can't run in parallel

### ISSUE THREAD

**Issue by alippai** [conda-forge/arrow-cpp-feedstock#1060]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I can't reproduce it, but it "feels like" if multiple activations of the same environment happens in parallel (on NFS), then the activation fails with:
```
ln: failed to create symbolic link '/.../share/gdb/auto-load//.../lib/libarrow.so.1200.0.0-gdb.py': File exists
```

### Installed packages

```shell
libarrow-12.0.0-h6564b11_2_cpu.conda
```

### Environment info

```shell
shell level : 2
conda version : 22.11.1
conda-build version : 3.21.9
python version : 3.10.8.final.0
```

**Comment by alippai** [comment]
@h-vetinari @maresb any ideas how to fix this? `ln -f` would help with the creation, but some condition for the `rm` might be useful too?

**Comment by maresb** [comment]
Hmm, looking again at `activate.sh`, I see that in the `ln -s` command I forgot to replace the target with `"$target"`, but this shouldn't make a difference. (To be noted for next time someone edits that file. :wink:)

I already have a condition on the `rm`... see the block under `# If the directory is not writable, nothing can be done`.

Could you please investigate what's going on with the link target? Are you able to delete it?

I wonder if there is some strange permission thing going on.

**Comment by maresb** [comment]
I think https://github.com/conda-forge/arrow-cpp-feedstock/pull/1065 will take care of it.

**Comment by alippai** [comment]
@maresb Thanks, LGTM.

**Comment by h-vetinari** [comment]
@alippai, the linux-64 are online now, would be nice if you could confirm that this fixes your problem. :)

**Comment by alippai** [comment]
I can confirm build no. 5 works
