### ISSUE TITLE
Workaround on Windows for `CUDA_HOME` & `CUDA_PATH`?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/arrow-cpp-feedstock#1080]
Saw this workaround with comment. Is this workaround still needed? Does it still need upstreaming?

https://github.com/conda-forge/arrow-cpp-feedstock/blob/5079e411defdf806f7a16194e2adcabefa78c8ab/recipe/build-arrow.bat#L10-L12

Also noticed `pyarrow` doesn't have the same workaround. So was wondering if maybe this was already fixed

https://github.com/conda-forge/arrow-cpp-feedstock/blob/5079e411defdf806f7a16194e2adcabefa78c8ab/recipe/build-pyarrow.bat#L23-L25

**Comment by h-vetinari** [comment]
> Is this workaround still needed? Does it still need upstreaming?

No idea... 🙃 
We could try in #1079, which seems as great a time as any to touch cuda-related things.
