### ISSUE TITLE
How about loosing run_exports?

### ISSUE THREAD

**Issue by kou** [conda-forge/arrow-cpp-feedstock#1096]
### Comment:

We've tightened `run_exports` by https://github.com/conda-forge/arrow-cpp-feedstock/pull/108 .
It's happen before Apache Arrow C++ 1.0.0.

Apache Arrow C++ follows Semantic Versioning since 1.0.0. So users can use any Apache Arrow C++ version even if they have the same major version. For example, an user who wants to use Apache Arrow C++ 12 can use one of 12.0.0, 12.0.1 or 12.1.0.

**Comment by h-vetinari** [comment]
Thanks for opening this issue!

> Apache Arrow C++ follows Semantic Versioning since 1.0.0.

There's an important difference here between SemVer, which usually covers the API, and what we do with the `run_export` which needs to cover the ABI. Basically, we need to be reasonably sure that arrow never (incompatibly) modifies exported symbols in a patch release.

**Comment by h-vetinari** [comment]
Ah, just saw your comment in https://github.com/conda-forge/arrow-c-glib-feedstock/pull/11
> > Is that also applicable on an ABI-level?
> 
> Yes.

OK then, I'll switch the run-export to use `max_pin="x"`, which means that anything until the next major version will be considered compatible.

How do you feel about backporting this? I would backport it at least so v11 & v10. v9 is also still supported here for now, but the further back we go, the more we risk breaking something that's already working fine (and realistically, there will be no more new patch releases for these branches anyway, so I guess it's really not necessary...)

**Comment by jorisvandenbossche** [comment]
> > Is that also applicable on an ABI-level?
> 
> 
> Yes.

@kou do we actually document those guarantees somewhere?

**Comment by kou** [comment]
Sorry. I forgot to answer it.

In general, I think that projects that follow Semantic Versioning must guarantee it.
If it is ambiguous, how about discuss this on `dev@arrow.apache.org`?
