### ISSUE TITLE
Updating LLVM

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/arrow-cpp-feedstock#116]
Looks like [LLVM is pinned to 7]( https://github.com/conda-forge/arrow-cpp-feedstock/blob/db5dfc9b4216cf39a4b4721f02e9703b55b33829/recipe/meta.yaml#L38-L39 ). Is this needed for some reason? If not, would it be possible to upgrade to a more recent version (like 9)?

**Comment by xhochy** [comment]
This is required because upstream only builds & tests against 7 at the moment.

**Comment by jakirkham** [comment]
Are there plans to update LLVM upstream?

**Comment by h-vetinari** [comment]
@jakirkham: Are there plans to update LLVM upstream?

See [ARROW-6841](https://issues.apache.org/jira/browse/ARROW-6841) resp. apache/arrow#6266

**Comment by xhochy** [comment]
We have updated to 8. Versions 9/10 will take their time but one should watch upstream for that.

**Comment by jakirkham** [comment]
Thanks @xhochy! 😄
