### ISSUE TITLE
Remove `track_features` for cuda builds?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/arrow-cpp-feedstock#1169]
We've been weighing down the CUDA builds ever since they got added in #137.

Now that conda versions with `__cuda` are way more widespread, I think we could remove the track_features, and just rely on the (already existing!) run-dependence on `__cuda`, to ensure that people don't download the GPU bits senselessly.

Thoughts @conda-forge/arrow-cpp?

CC @conda-forge/core

**Comment by hmaarrfk** [comment]
I've found that the build number strategy is easier to understand in practice. 

I'm in favor of removing track feature.

**Comment by h-vetinari** [comment]
Closing as duplicate of #1425, which contains more discussion. Planning to do this as of v18
