### ISSUE TITLE
How are arrow-cpp and pyarrow related?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/arrow-cpp-feedstock#124]
It looks like `arrow-cpp` is [building the Python pieces]( https://github.com/conda-forge/arrow-cpp-feedstock/blob/ce61086aa1a596d1d26c815747a2e857785f9ae1/recipe/build.sh#L41 ). However there is also `pyarrow`, which is doing the [more typical Python build]( https://github.com/conda-forge/pyarrow-feedstock/blob/93a473b926603cc6a260701c01de0dc4f991013b/recipe/build.sh#L22-L25 ). Am trying to understand what Python pieces are included in `arrow-cpp` vs. what are included in `pyarrow`. Help understanding this would be most welcome 🙂

**Comment by pearu** [comment]
IIRC, the arrow-cpp python piece provides tools for Arrow C++ to/from Arrow Python C/API conversion and pyarrow exposes Arrow Python C/API to Python using Cython.
I hope that this simplistic answer is more-or-less correct :)
@wesm, @pitrou ?

**Comment by h-vetinari** [comment]
Xref https://github.com/conda-forge/pyarrow-feedstock/issues/107

**Comment by jakirkham** [comment]
Thanks for the answer (sorry for the delayed reply). Let's go ahead and close.

**Comment by h-vetinari** [comment]
I'm planning (and the sentiment seems shared by @pearu) to try bringing pyarrow in the recipe here.
