### ISSUE TITLE
How to create conda env with CUDA enabled arrow-cpp?

### ISSUE THREAD

**Issue by pearu** [conda-forge/arrow-cpp-feedstock#134]
With the current state, creating a conda environment using
```
conda create -c conda-forge -n test-arrow-cpp arrow-cpp "arrow-cpp-proc=*=cuda"
```
leads to
```
The following NEW packages will be INSTALLED:
  <snip>
  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.17.0-py38h9d6855f_0
  arrow-cpp-proc     conda-forge/linux-64::arrow-cpp-proc-1.0.0-cuda
  <snip>
```
which is wrong as arrow-cpp-0.17.0-py38h9d6855f_0 does not have CUDA enabled.

Also
```
conda create -c conda-forge -n test-arrow-cpp "arrow-cpp=0.16" "arrow-cpp-proc=*=cuda"
```
will lead to wrong packages:
```
  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.16.0-py38h9d6855f_4
  arrow-cpp-proc     conda-forge/linux-64::arrow-cpp-proc-1.0.0-cuda
```

However
```
conda create -c conda-forge -n test-arrow-cpp "arrow-cpp=*=*cuda"
```
gives correct result:
```
  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.16.0-py38h25a4a40_5_cuda
```

The question of this issue is why the usage of `arrow-cpp-proc=*=cuda` is ineffective?

I guess the answer lies in the fact that `arrow-cpp-0.16*_4` and `arrow-cpp-0.17*_0` use old meta.yaml that is not `arrow-cpp-proc` aware.

As a fix, `arrow-cpp-feedstock` should start using the new `arrow-cpp-proc`-aware `meta.yaml` but it seems that the issue will continue to persist until `arrow-cpp-0.18` will be packaged with the new `meta.yaml` only. What do you think?

CC: @jakirkham @xhochy @isuruf

**Comment by xhochy** [comment]
We should patch the repodata for the older `arrow-cpp` packages to also depend on `arrow-cpp-proc`, see the repo https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by jakirkham** [comment]
Thanks @xhochy! 😀
