### ISSUE TITLE
Disable(d) ppc64le support due to maintenance burden

### ISSUE THREAD

**Issue by xhochy** [conda-forge/arrow-cpp-feedstock#143]
I'm going to remove `ppc64le` builds from `arrow-cpp` as they cause a lot of headaches. Building on Travis fails in over 80% of cases. As of yesterday, I'm also no longer able to press restart in Travis, making it even harder for me. Building things in emulation takes way too long and thus we have to wait really long until we can push any change to the Apache Arrow stack.

As this is probably a bit of a precedent, pinging as an FYI: @conda-forge/help-ppc64le @conda-forge/core @jayfurmanek

**Comment by jakirkham** [comment]
Maybe we can try [cross-compiling]( https://github.com/conda-forge/llvmdev-feedstock/pull/95/files#diff-c48034b662d2a516a39beb01e6a756df )?

**Comment by mariusvniekerk** [comment]
Worth trying the cross compile.

**Comment by jglaser** [comment]
Is there any intent on reviving ppc64le support? Happy to look into it.

**Comment by xhochy** [comment]
Re-enable it in the `conda-forge.yml` and see whether it passes. Travis seems to be more stable in the past weeks so this may be less of a burden now.

**Comment by jakirkham** [comment]
Fixed with PR ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/196 )

**Comment by xhochy** [comment]
Disabled again as Travis annoyed me again (time to run CI and one job was crashing).

If we really want to have this, there needs to be some effort to do the `ppc64le` with e.g. cross-compiling. Emulated or Travis is not a viable option.

**Comment by jakirkham** [comment]
We tried both in PR ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/196 ). As native builds were working, we went with those.

**Comment by xhochy** [comment]
Yes, both approaches aren't nice for maintenance. Thus I would prefer a cross-compiling solution.

**Comment by xhochy** [comment]
Happily providing `ppc64le` since some builds again.
