### ISSUE TITLE
PyArrow cuda packages have `cudatoolkit 9.2|9.2.*` dependency

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/arrow-cpp-feedstock#149]
See `_cuda` packages here: https://anaconda.org/conda-forge/pyarrow/files?version=0.17.1

It looks like the `ignore_run_export` from arrow-cpp doesn't carry over to pyarrow in the split package?

**Comment by kkraus14** [comment]
cc @jakirkham @pearu @isuruf for if you have any ideas as to what's going on here

**Comment by pearu** [comment]
The pyarrow output lacks `ignore_run_export`, it might worth trying to add there.

Btw, the hash value `1234567` of the package is suspiciously regular.

**Comment by isuruf** [comment]
> The pyarrow output lacks ignore_run_export, it might worth trying to add there.

That's the issue here.

**Comment by kkraus14** [comment]
Is it expected behavior that even though PyArrow only inherits the `cudatoolkit` dependency from arrow-cpp that it doesn't inherit the `ignore_run_exports`?

**Comment by jakirkham** [comment]
I'm working on a PR atm.

**Comment by isuruf** [comment]
> Is it expected behavior that even though PyArrow only inherits the cudatoolkit dependency from arrow-cpp that it doesn't inherit the ignore_run_exports?

I'm not sure I understand. PyArrow has `compiler('cuda')` in its build requirements and therefore it needs `ignore_run_exports`.

**Comment by jakirkham** [comment]
That's right. Anything that adds the `{{ compiler('cuda') }}` would need its own `ignore_run_exports` as the compiler is what adds this constraint.

Submitted PR ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/150 ) if people can take a look.

**Comment by kkraus14** [comment]
> I'm not sure I understand. PyArrow has `compiler('cuda')` in its build requirements and therefore it needs `ignore_run_exports`.

I think the explanation here is that I completely overlooked this and had a brain fart 😆. Thanks!

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/cf-mark-broken/pull/80 ) to mark the incorrectly constrained packages as `broken`.
