### ISSUE TITLE
`pyarrow=1.0.1`, `boost-cpp=1.7.4`, `python=3.8` are currently in a broken state

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/arrow-cpp-feedstock#174]
To use `boost-cpp=1.7.4` with `python=3.8` you need `arrow-cpp=1.0.1=py38hb4b7afc_3*`. This breaks if using `pyarrow` as there's no `pyarrow` build associated with that `arrow-cpp` version and `pyarrow` pins to exact builds of `arrow-cpp`.

Relevant `arrow-cpp` info: https://anaconda.org/conda-forge/arrow-cpp/files/modal/info/5f62080f78d4370a3ca2bad5

**Comment by kkraus14** [comment]
Also, looks like this isn't the only issue, with the `_3` builds of pyarrow, the python 3.6 and 3.7 builds point to the `arrow-cpp`  built with boost 1.74 and can't point to a boost 1.72 build.

**Comment by jakirkham** [comment]
FWIW here's [the relevant build on `master`]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=210302&view=logs&jobId=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&j=3a25022a-f08c-5c04-be7d-d279a7fc48ef&t=03fcd6e6-009d-576b-db27-27f5032302f9 ). Also [attached]( https://github.com/conda-forge/arrow-cpp-feedstock/files/5242037/linux_64_boost_cpp1.74.0cuda_compiler_version9.2python3.8.____cpython.txt ).

**Comment by jakirkham** [comment]
It looks like [this is the relevant `pyarrow` package]( https://anaconda.org/conda-forge/pyarrow/files/modal/info/5f62034ba58f0d0a15374391 ).

**Comment by jakirkham** [comment]
I could be mistaken, but do we want [this `arrow-cpp` package]( https://anaconda.org/conda-forge/arrow-cpp/files/modal/info/5f62080f78d4370a3ca2bad5 ) instead?

**Comment by kkraus14** [comment]
Presumably I should be able to use either boost 1.72 or boost 1.74. Right now there's only 3 sets of builds, 1 per Python version, and each build ties to a specific arrow-cpp build which dictates a specific boost version. I'd assume we'd need either 6 pyarrow builds as well or to relax the arrow-cpp pinning.

**Comment by jakirkham** [comment]
I count 12 (CUDA/CPU, Boost 1.72.0/1.74.0, and Python 3.6-3.8) for `arrow-cpp`.

My guess is `pyarrow` should be usable with `arrow-cpp` that is built with `boost-cpp` 1.72 or 1.74 equally. If that's true, pinning to the hash is overly constrained. If that's not true, maybe `pyarrow` also needs a `boost-cpp` dependency.

**Comment by jakirkham** [comment]
@xhochy, would be good to get your take on which approach makes more sense 🙂

**Comment by xhochy** [comment]
`arrow-cpp` shouldn't introduce a `boost` dependency on `pyarrow`, so I'm a bit confused how this is reflected in downstream dependencies. With the current pinning, only one of the `arrow-cpp-py38` variants will be used by `pyarrow` but it shouldn't matter which ones of these.

**Comment by jakirkham** [comment]
It doesn’t. Instead [the exact pinning of `arrow-cpp` in `pyarrow`]( https://github.com/conda-forge/arrow-cpp-feedstock/blob/e957a944a33d87e6191bc2c3c45fa48f90813659/recipe/meta.yaml#L183 ) effectively ties `pyarrow` to an `arrow-cpp` package built against one of the `boost-cpp` versions. Hope that is more clear 🙂

**Comment by xhochy** [comment]
It does actually. See my opened PR. We have a `run_constraint` in there that isn't needed and thus actually introduces a boost constrained on dependencies.

**Comment by jakirkham** [comment]
Gotcha, maybe I was misunderstanding then. Anyways thanks for tracking this down and fixing :)

**Comment by xhochy** [comment]
Seems like not everything is resolved. I have some failing builds that report issues with `pyarrow` directly depending on `boost-cpp`: https://github.com/conda-forge/turbodbc-feedstock/pull/46 @jakirkham @kkraus14  is this the same as you are seeing?

```
Package boost-cpp conflicts for:
arrow-cpp=1.0.1 -> thrift-cpp[version='>=0.13.0,<0.14.0a0'] -> boost-cpp[version='>=1.70.0,<1.70.1.0a0|>=1.72.0,<1.72.1.0a0']
pyarrow -> arrow-cpp=0.11.0 -> boost-cpp[version='1.66.0|>=1.66.0,<1.66.1.0a0|>=1.67.0,<1.67.1.0a0']
boost=1.74.0 -> boost-cpp=1.74.0
pyarrow -> boost-cpp[version='>=1.68.0,<1.68.1.0a0|>=1.70.0,<1.70.1.0a0|>=1.72.0,<1.72.1.0a0']
boost-cpp=1.74.0
```

**Comment by kkraus14** [comment]
That looks a bit different than what we were seeing. We were seeing that there was only a single pyarrow candidate for `pyarrow=1.0.1`, `python=3.8` and `arrow-cpp-proc=*=cuda`, and that pyarrow candidate pinned to an exact build of `arrow-cpp` which had a `run_constrained` of `boost-cpp=1.72.0`

**Comment by kkraus14** [comment]
Things seem to be solving as expected now with both `boost-cpp=1.74` and `boost-cpp=1.72`, though it looks like we're producing "duplicate" `arrow-cpp` builds for the different boost versions and only one of the two builds can be used with pyarrow.

**Comment by jakirkham** [comment]
Is it possible that something is just lingering locally that's causing some issues? Maybe using `conda clean` would help?

**Comment by xhochy** [comment]
@kkraus14 @jakirkham Everything good now?

**Comment by kkraus14** [comment]
@xhochy users won't fail to solve or end up in a broken state now, but things are still in a non-ideal state. There's still currently two builds of arrow-cpp being produced for a given python version and build process, take these for example:
- `arrow-cpp-1.0.1-py38h3cf7a2b_5_cpu`: https://anaconda.org/conda-forge/arrow-cpp/files/modal/info/5f65045c78d4370a3c4e4bb2
- `arrow-cpp-1.0.1-py38h7fd2328_5_cpu`: https://anaconda.org/conda-forge/arrow-cpp/files/modal/info/5f64fca8d2ff9009fd39ed14

Now for pyarrow there's only one build:
- `pyarrow-1.0.1-py38h9235441_5_cpu`: https://anaconda.org/conda-forge/pyarrow/files/modal/info/5f64fca8d2ff9009fd39ed1b

This pyarrow build has a dependency on:
- `arrow-cpp 1.0.1 py38h7fd2328_5_cpu`

Now imagine I do something like this:
```
conda create -n arrow_test "python=3.8" "arrow-cpp=1.0.1" "arrow-cpp-proc=*=cpu"
conda install "pyarrow=1.0.1"
```

The environment creation command currently solves to `arrow-cpp-1.0.1-py38h3cf7a2b_5_cpu` and then the pyarrow installation command has to "downgrade" the `arrow-cpp` package to the other build unnecessarily.

**Comment by jakirkham** [comment]
I think that is because we build against 2 Boost versions still. However that doesn't appear in any visible way in the end product since Boost is now treated as an internal dependency ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/175 ). Though I could be wrong about this.

**Comment by xhochy** [comment]
These builds should be no issue. We have the same in `thrift-cpp`. Once the migration is done, we'll be back to a single build again.

**Comment by jakirkham** [comment]
Cool, I think we are good then unless @kkraus14 has anything else 🙂

**Comment by kkraus14** [comment]
Sounds good to me, closing this issue as it's now resolved.
