### ISSUE TITLE
re-render for np113

### ISSUE THREAD

**Issue by jreback** [conda-forge/arrow-cpp-feedstock#24]
@jakirkham can I force a re-render to build for numpy 1.13 on this (and a couple downstream packages) ?

do we need to push a re-render PR (that is empty)?

eg. for recipes with ``numpy x.x``

**Comment by jreback** [comment]
e.g. looks like this: https://github.com/conda-forge/matplotlib-feedstock/commit/91cd2b49bd570167506da0761ac6f4ae92ee4aef

but how was this kicked off?

**Comment by wesm** [comment]
We need to upgrade to 0.4.1 too

**Comment by jakirkham** [comment]
Yes, re-rendering will add the new NumPy version to the matrix.
