### ISSUE TITLE
[warning] failed package validation and/or copy for commit 989268e11365101c9d72a09cd284e303e99873fb

### ISSUE THREAD

**Issue by conda-forge-daemon** [conda-forge/arrow-cpp-feedstock#269]
Hi @conda-forge/arrow-cpp! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.

error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/linux-ppc64le/pyarrow-2.0.0-py37h66123b5_14_cpu.tar.bz2

**Comment by jakirkham** [comment]
Was this just an old CI job that was being restarted?

**Comment by h-vetinari** [comment]
> Was this just an old CI job that was being restarted?

Yes. Not that old, but just before the token brouhaha
