### ISSUE TITLE
libstdcxx-ng>=9.3.0 requirement by arrow-cpp

### ISSUE THREAD

**Issue by harelwa** [conda-forge/arrow-cpp-feedstock#455]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hi,

I have a requirements conflict that is caused by **arrow-cpp** version restriction **libstdcxx-ng >=9.3.0**

I'll first note the versioning details --

- **arrow-cpp=4.0.1=py37h628fdca_0_cpu** requires **libstdcxx-ng >=9.3.0**
- **libstdcxx-ng >=9.3.0** means **libstdc++.so.6.0.28**
- **Ubuntu:18.04** comes with **libstdc++.so.6.0.25** which is the equivalent of **libstdcxx-ng=8.2**
- **pyarrow** + **arrow-cpp** are tested also on **Ubuntu:18.04** regardless of conda, relying on pre installed **libstdc++**
- there are breaking api changes between **libstdc++.so.6.0.25** and **libstdc++.so.6.0.28**

Unfortunately, my cpp package can _not_ run with  **libstdcxx-ng=9.3** [ **libstdc++.so.6.0.28** ] due to api differences, but still needs to be installed with **arrow-cpp** latest version [ 4.0.1 ]

But, as **arrow** is tested on **ubuntu:18.04**, it thus relies on OS installed libstd [ e.g. for none conda users ]

So, I basically have two questions:

1. why is this restriction necessary ?
2. where is this restriction specified ? it's a level one requirement according to info ( listed below )it's not mentioned in the recipe **meta.yaml**, and I could not find it in the globally pinned packages explained in [conda-forge docs ](https://conda-forge.org/docs/maintainer/pinning_deps.html#globally-pinned-packages)

```
>$conda search arrow-cpp=4.0.1=py37h628fdca_0_cpu --info
arrow-cpp 4.0.1 py37h628fdca_0_cpu
----------------------------------
file name   : arrow-cpp-4.0.1-py37h628fdca_0_cpu.tar.bz2
name        : arrow-cpp
version     : 4.0.1
build       : py37h628fdca_0_cpu
build number: 0
size        : 22.2 MB
license     : Apache-2.0
subdir      : linux-64
url         : https://artifactory.sddc.mobileye.com/artifactory/api/conda/conda-condaforge-remote/linux-64/arrow-cpp-4.0.1-py37h628fdca_0_cpu.tar.bz2
md5         : 384bea498466854edc3a43de493510fe
timestamp   : 2021-05-28 15:25:35 UTC
constraints : 
  - arrow-cpp-proc * cpu
dependencies: 
  - aws-sdk-cpp >=1.8.186,<1.8.187.0a0
  - brotli >=1.0.9,<2.0a0
  - bzip2 >=1.0.8,<2.0a0
  - c-ares >=1.17.1,<2.0a0
  - gflags >=2.2.2,<2.3.0a0
  - glog >=0.5.0,<0.6.0a0
  - grpc-cpp >=1.38.0,<1.39.0a0
  - libgcc-ng >=9.3.0
  - libprotobuf >=3.16.0,<3.17.0a0
  - libstdcxx-ng >=9.3.0
  - libthrift >=0.14.1,<0.15.0a0
  - libutf8proc >=2.6.1,<3.0a0
  - lz4-c >=1.9.3,<1.9.4.0a0
  - numpy >=1.16,<2.0a0
  - orc >=1.6.8,<1.6.9.0a0
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
  - re2 >=2021.4.1,<2021.4.2.0a0
  - snappy >=1.1.8,<2.0a0
  - zlib >=1.2.11,<1.3.0a0
  - zstd >=1.5.0,<1.6.0a0
``` 

Thanks in advance,
Harel

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
`arrow-cpp` is built on conda-forge using conda-forge's toolchain with GCC 9.3 on Linux. This introduces the limitation on `libstdcxx-ng>=9.3`. conda managed environments are independent of the Linux distribution that you use for you main system, i.e. they are also not using the system's `libstdc++`. `libc` is the only library that is used from your distribution (here: Ubuntu) everything else is self-contained in the conda environment. You should not mix linkage between conda-supplied libraries and system ones. Rather you should build everything in your conda environment using conda-forge's compiler toolchain to support things working together.
