### ISSUE TITLE
Build with flatbuffers

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/arrow-cpp-feedstock#460]
It looks like we are not building with `flatbuffers`, but maybe we should be. Though please let me know if I'm missing something

**Comment by jayfurmanek** [comment]
Arrow does have the flatbuffers cpp headers copied over to its codebase:
https://github.com/apache/arrow/tree/master/cpp/thirdparty/flatbuffers/include/flatbuffers

Perhaps that is all it needs to build?  CMake doesn't explicitly look for flatbuffers.
If that's the case maybe the recipe needs a runtime dep listed, however, to ensure its there at runtime.

**Comment by jayfurmanek** [comment]
Sounds like it's all "under the hood"

http://arrow.apache.org/faq/#:~:text=Flatbuffers%20is%20a%20low%2Dlevel%20building%20block%20for%20binary%20data%20serialization.&text=The%20Arrow%20file%20format%20does,for%20optimal%20access%20and%20computation.

**Comment by xhochy** [comment]
Arrow C++ only use the small header part that is bundled and thus also has no runtime dependency on `flatbuffers`. It's all coming with the Arrow C++ source code already.
