### ISSUE TITLE
After importing pyarrow importing mysqldb throws exception

### ISSUE THREAD

**Issue by alippai** [conda-forge/arrow-cpp-feedstock#636]
Somehow pyarrow modifies the conda environment in a way that mysqldb (mysqlclient) cannot be imported. Trying to import MySQLdb throws error libstdc++.so.6 error. `cannot allocate memory in static TLS block`.

**Comment by alippai** [comment]
https://petastorm.readthedocs.io/en/latest/troubleshoot_include.html this looks like a similar (reverse) issue

**Comment by xhochy** [comment]
I would expect that the migitation for this problem is in `MySQLdb`, we did disable static TLS and friends as good as possible in `arrow-cpp`. Can you still post a traceback from the error to confirm that?

**Comment by alippai** [comment]
Yes, I'll try to set up a minimal repro and collect the traceback/logs.

**Comment by h-vetinari** [comment]
This sounds like https://github.com/conda-forge/conda-forge.github.io/issues/1551, which is affected by the order in which libgomp is loaded (and thus affected by the order of certain imports).

@alippai, did you encounter that issue again afterwards?

**Comment by h-vetinari** [comment]
Seeing that there hasn't been a response in ~5 months, I'm closing this issue. Please let us know if it needs reopening.
