### ISSUE TITLE
Is `python` a necessary run dependency for `arrow-cpp`?

### ISSUE THREAD

**Issue by mfansler** [conda-forge/arrow-cpp-feedstock#712]
One of my pure R environments ended up installing`python` today. Tracing back the culprit `r-*` package, I found that the `r-pins` package depends on `arrow-cpp`, and this includes `python` as a run dependency. Why is that? Is this library truly dependent on having Python installed?

**Comment by jakirkham** [comment]
Yes, please see issue ( https://github.com/conda-forge/arrow-cpp-feedstock/issues/124 ) for more context
