### ISSUE TITLE
Did you really want so many abi branches

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/arrow-cpp-feedstock#757]
### Comment:

Seems like we have quite a few ABI branches. I would like to help get the abseil migration complete but it seems like I would have to backport quite a few changes. Thoughts?

**Comment by hmaarrfk** [comment]
PR in question: https://github.com/conda-forge/arrow-cpp-feedstock/pull/749

**Comment by xhochy** [comment]
Yes, `arrow-cpp` consumers are sometimes quite slow-moving but Arrow doesn't have good API/ABI compatibility. Thus we also support the last 4ish versions of it, too.

**Comment by hmaarrfk** [comment]
Thanks for confirning
