### ISSUE TITLE
Undeclared dependency on very recent libcxx

### ISSUE THREAD

**Issue by batterseapower** [conda-forge/arrow-cpp-feedstock#771]
### Comment:

The linux build of arrow-cpp 7.0.0 on conda-forge (py310hf3556ec_6_cpu) dynamically loads a symbol containing GLIBCXX_3.4.30. Unfortunately mamba sometimes pulls in libstdcxx-ng 11.2.0 which only exports GLIBCXX_3.4.29. You can work around this by forcing the environment to include libstdcxx-ng 12.1.0 instead (which was only released 10 days ago) but my layman's understanding is that your arrow-cpp package should probably declare a dependency on this very recent libstdcxx-ng in order to avoid the older libstdcxx-ng being a valid solution.

Other versions of arrow-cpp are affected: the older Linux build of arrow-cpp 7.0.0 (py310h68f40c4_4_cpu) did not have this libcxx dependency, but the new 8.0.0 build py310hf3556ec_1_cpu does have it.

**Comment by kkraus14** [comment]
Fixed by https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/75
