### ISSUE TITLE
Please do only one PR/build at a time

### ISSUE THREAD

**Issue by isuruf** [conda-forge/arrow-cpp-feedstock#825]
With 70 jobs for each build, this feedstock has been holding up the queue multiple times in the last week and degrades the QoS of other feedstocks. For eg: there are currently 2 PRs and 1 main build which is 210 jobs.

cc @kkraus14, @xhochy

**Comment by xhochy** [comment]
👍 Noted.

**Comment by kkraus14** [comment]
👍 noted as well, apologies @isuruf

**Comment by isuruf** [comment]
Thanks. @xhochy and @kkraus14

**Comment by jakirkham** [comment]
Maybe we should take a closer look on how migrations are handled given these issues? Some of the PRs being added are by bots. Canceled a bunch of jobs from bot migration PRs (see xref'd PRs above)
