### ISSUE TITLE
Unpin boost-cpp

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/arrow-cpp-feedstock#850]
Since https://github.com/conda-forge/arrow-cpp-feedstock/pull/234, boost-cpp is not managed by the global pinning here, which looks a bit risky. boost-cpp [does not have](https://github.com/conda-forge/boost-cpp-feedstock/pull/82) a run-export, so thisn't viral in terms of incompatibility at least, but depending on which parts of boost are used, this could still bite us.

Unpinning boost would mean having yet more migration PRs, so if we know we're using the header-only portions, keeping the lower bound might actually be better.

Thoughts @conda-forge/arrow-cpp?

**Comment by kkraus14** [comment]
The main library uses header only modules and doesn't leak them into public interfaces. The tests, benchmarks, and examples use boost modules that require shared libraries, but we don't build any of those as part of the conda-forge packaging.

I agree not managing it is a bit risky, but we don't need to necessarily follow the global pinning here.

**Comment by h-vetinari** [comment]
> The tests, benchmarks, and examples use boost modules that require shared libraries, but we don't build any of those as part of the conda-forge packaging.

Presumably those are just the tests for arrow-cpp? Because we do explicitly package & publish `pyarrow-tests`

**Comment by kkraus14** [comment]
> Presumably those are just the tests for arrow-cpp? Because we do explicitly package & publish `pyarrow-tests`

Yea, just for arrow-cpp

**Comment by h-vetinari** [comment]
So, IIUC, the takeaway here is to not unpin boost (but document that we're only using the headers; maybe even enforce that through deleting the libs...), and close all the boost PRs so the migrator can move forward. I checked that the builds already use 1.80 in the host environment, so there really shouldn't be anything to do.

If for some reason I misunderstood something (e.g. with the `pin_run_as_build` stuff) and dependency resolution fails for the downstream children, I'll happily reinstate the PRs (I have them locally).

**Comment by h-vetinari** [comment]
Fixed by #1180 and related PRs
