### ISSUE TITLE
Release 10.0.0 ETA

### ISSUE THREAD

**Issue by ncclementi** [conda-forge/arrow-cpp-feedstock#912]
### Comment:

Hi folks, is there an estimate on when we would have pyarrow 10.0.0 released in conda-forge?
Thanks

**Comment by akrherz** [comment]
@ncclementi You may be having dependency issues within your environment attempting to install it.  For example, this works 
```
$ mamba create -n dev python=3.10 pyarrow=10
...
 + pyarrow                   10.0.1  py310hba8c93b_1_cpu  conda-forge/linux-64        3MB
...
```

Within your environment, you can try this command and you might get a bit cryptic error, like I do, which denotes dependency issues still at play here.

```
$ mamba install pyarrow=10
Could not solve for environment specs
Encountered problems while solving:
  - nothing provides __cuda needed by tensorflow-2.10.0-cuda112py310he87a039_0
```

**Comment by h-vetinari** [comment]
That's because tensorflow has not been rebuilt for libgrpc 1.49 yet (tf builds take a long time because they need to be done manually).

**Comment by jakirkham** [comment]
Also would suggest raising questions about [Tensorflow updates to that feedstock]( https://github.com/conda-forge/tensorflow-feedstock/issues )
