### ISSUE TITLE
Rebuild maintenance branches for aws-sdk-cpp 1.9 & openssl 3?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/arrow-cpp-feedstock#918]
We released arrow v10 a couple of days ago built against aws-sdk-cpp 1.9, the first such build after a long time, since we were previously stuck on 1.8 due to https://github.com/aws/aws-sdk-cpp/issues/1809

I've asked on all the related issues that I'm aware of if someone could test with v10 to see if the original issue persists or is gone (since we cannot test this on our infra).
https://github.com/conda-forge/arrow-cpp-feedstock/issues/567
https://github.com/aws/aws-sdk-cpp/issues/1809
https://issues.apache.org/jira/browse/ARROW-15141
https://github.com/huggingface/datasets/issues/3310

I think after a certain time we can probably assume that things went fine (and IMO the [fix](https://github.com/awslabs/aws-c-io/pull/515) is pretty unambiguous).

Assuming we can agree on this among @conda-forge/arrow-cpp, I'd like to backport this to the maintenance branches, because to continue with the OpenSSL 3 migration, we need aws-sdk-cpp 1.9. And not having OpenSSL 3 for arrow <10 is quite painful for libraries wanting to build against all arrow versions in the global pinning, c.f. https://github.com/conda-forge/gdal-feedstock/pull/679

Thoughts?

**Comment by jakirkham** [comment]
Applying the same migrations to the branches covered by ABI migrations makes sense. Maybe it is worth applying all migrations together?

**Comment by h-vetinari** [comment]
Generally yes, I'd agree to merge migrations for all ABI branches. In this case it's more like a feature though to use aws-sdk-cpp 1.9 after it's been on 1.8 for the affected arrow versions for more than a year, all the more due to the potential for regressions.

I'd be much happier if I heard from anyone affected by the original issue on AWS to confirm it doesn't happen with arrow 10 anymore (the thinking was to only do one arrow version that bumps aws-sdk-cpp initially, so that marking things as broken is less painful, if it becomes necessary).

Applying both migrations together makes sense of course (though I dread how many restarts it will take to get a passing run on 8.0.x and 9.0.x after the build matrix doubles in size)

**Comment by h-vetinari** [comment]
[Confirmed](https://github.com/conda-forge/arrow-cpp-feedstock/issues/567#issuecomment-1344764356) to be fixed - thanks a lot @jdblischak! :)

**Comment by h-vetinari** [comment]
> Maybe it is worth applying all migrations together?

I have prepared the following PRs, which also backport some clean-ups from #875 (and making sure we enable all bindings/libs for that are available for the respective version):
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/900
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/874
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/873
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/872

The 8.0.x & 9.0.x PRs will need a gratuitous number of restarts (or we drop CUDA+aarch on those branches), but otherwise these should all be fine/ready.

**Comment by h-vetinari** [comment]
@pitrou @xhochy 
Would appreciate your thoughts on this :)

**Comment by xhochy** [comment]
If it works, let's move forward and apply the migration to these branches! 🚀

**Comment by h-vetinari** [comment]
All done now. 🤞 we get no regressions
