### ISSUE TITLE
Split package?

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/arrow-cpp-feedstock#93]
Should we split this package into a portion without python and one with the python bindings?

Feels a little weird that arrow-cpp requires a python to be installed at all times.

Thoughts?

**Comment by xhochy** [comment]
I would support that as I currently build R environments with `conda` and at some time I would also like to have ones without Python.

@wesm @kszucs Is that ok with you?

**Comment by kszucs** [comment]
Perhaps we should ship `libarrow_python` with the pyarrow feedstock.

**Comment by xhochy** [comment]
No, this would complicate our packaging even more, I would use the `outputs` feature of `conda-build` here and just define `libarrow_python` as a separate output that has the Python dependency. Then all the magic lives in the `meta.yaml`.

**Comment by kszucs** [comment]
Forgot about the outputs section
