### ISSUE TITLE
cudatoolkit constraint or `__cuda` run-dep?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/arrow-cpp-feedstock#942]
In #873 @kkraus14 commented on the diff:
```diff
-        - cudatoolkit >=9.2  # [cuda_compiler_version != "None"]
+        - cudatoolkit >={{ cuda_compiler_version_min }}  # [cuda_compiler_version != "None"]
```

> @kkraus14: This was intentional since Arrow only uses the CUDA driver library

> @h-vetinari: Yes, that's why it's set to the minimum? I.e. aarch it's 11, and `cuda_compiler_version_min` takes care of that on a cf level?
> 
> Or can we be sure that something compiled with CUDA 10.2 is still compatible with CUDA 9?

> @kkraus14: It doesn't use `nvcc` or any of the libraries in the `cudatoolkit` package. It only uses the CUDA driver library, `libcuda`, which is installed and versioned separately.
> 
> I believe this was added because `cudatoolkit` has a `__cuda` virtual package dependency to ensure that the driver version sufficiently supports the toolkit.
> 
> I'm not sure if there was a reason that we didn't use `__cuda` directly here. Regardless, if there is a reason I'd be more comfortable handling that in a follow up PR instead of this PR.

> @h-vetinari: Could be because that virtual package wasn't around yet at the time when arrow added CUDA support (not sure exactly about the timing)... So let's just use `__cuda`?

> @kkraus14: I'm not sure. It may have been weird solver behavior at the time or something else. Regardless, could we defer changing this to a follow up PR and just leave this as `cudatoolkit >=9.2` for now?

Undoing this on the maintenance branches has now "broken" the skip based on `cuda_compiler_version_min`:
```
  skip: true  # [cuda_compiler_version not in ("None", cuda_compiler_version_min)]
```
AFAICT because conda-smithy doesn't think that `cuda_compiler_version_min` is used in the recipe anymore (and so not populated in the `.ci_support/*.yml` files).

I'd like to keep the skip like that if possible (I continue to find to be a very elegant approach, rather than having to differentiate the minimum skips between aarches), but in any case, I'll have to change _something_ to unskip the CUDA builds, and so was wondering if we can decide on a way forward.

The way I see it, possible solutions are:
* Keep `cudatoolkit >=9.2` run-constraint (and trick conda-smithy to populate `cuda_compiler_version_min` (see https://github.com/conda-forge/arrow-cpp-feedstock/pull/940/commits/1f774a98d8a6fd1dc4d660aaf5ce0d8c7ae95ff9))
* Remove `cudatoolkit` run-constraint, replace with `__cuda` (as above)
* Drop CUDA 9.2 support

**Comment by h-vetinari** [comment]
For the time being, I worked around this by tricking conda-smithy, not changing anything else about the constraints.

**Comment by jakirkham** [comment]
Wonder if [`cuda-version`]( https://github.com/conda-forge/cuda-version-feedstock/blob/main/recipe/README.md ) could be a viable alternative here

**Comment by h-vetinari** [comment]
Definitely, once it's fully functional for CUDA 12, 11, 10 (and @kkraus14 asked not to raise the run-constraint past CUDA 9 not so long ago). How far back will `cuda-version` be available?

**Comment by jakirkham** [comment]
`cuda-version` is packaged all the way back to CUDA 9.2 (the first CUDA version added to conda-forge). Here's [the full list]( https://github.com/conda-forge/cuda-version-feedstock/blob/7e8b642c6bb4aeda93938a4cedc13895388937fe/recipe/conda_build_config.yaml ). We can always add more if we need. They are easy to add.

**Comment by jakirkham** [comment]
It has [`__cuda` with a matching lower bound in `run_constrained`]( https://github.com/conda-forge/cuda-version-feedstock/blob/7e8b642c6bb4aeda93938a4cedc13895388937fe/recipe/meta.yaml#L16 )


This is similar to [what `cudatoolkit` does]( https://github.com/conda-forge/cudatoolkit-feedstock/blob/531e4594992258568fe187bc5c4e40d8c9c57b27/recipe/meta.yaml#L576-L581 )

**Comment by kkraus14** [comment]
Yes, but someone without a GPU / CUDA driver could then get the CUDA variant since they wouldn't have a `__cuda` virtual package and therefore the `run_constrained` wouldn't kick in. It would then presumably fail at runtime at some point from failing to find `libcuda`

**Comment by jakirkham** [comment]
If we want to have a discussion about how we would like `cuda-version` to be used/behave, would suggest raising [a new issue in that feedstock]( https://github.com/conda-forge/cuda-version-feedstock/issues/new ). This would be a good time for that discussion

That said, the main value of `cuda-version` is it provides a knob to turn when selecting a specific CUDA Toolkit version and selecting a particular version of the CUDA Compiler used to build packages. This was something `cudatoolkit` did before, but it also installed a bunch of libraries (which we've learned not everyone wants). So `cuda-version` doesn't do this and instead is a lightweight package mainly useful for alignment

The challenge with `__cuda` is it doesn't really provide such a knob. Yes there is [`CONDA_OVERRIDE_CUDA`]( https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html?highlight=CONDA_OVERRIDE_CUDA#overriding-detected-packages ), but it doesn't really solve the problem. Other recipes or environment files can't constrain `__cuda`/`CONDA_OVERRIDE_CUDA`. It also may not always be obvious that `CONDA_OVERRIDE_CUDA` is set somewhere and affecting a Conda solve in the way that another package might

If I can suggest something, it would be using `cuda-version` for specifying the minimum CUDA version built with and adding `__cuda` only to require a GPU (similar to how OS-specific `noarch` packages have approached https://github.com/conda-forge/ipykernel-feedstock/pull/127 )

**Comment by kkraus14** [comment]
> That said, the main value of `cuda-version` is it provides a knob to turn when selecting a specific CUDA Toolkit version and selecting a particular version of the CUDA Compiler used to build packages. This was something `cudatoolkit` did before, but it also installed a bunch of libraries (which we've learned not everyone wants). So `cuda-version` doesn't do this and instead is a lightweight package mainly useful for alignment

The challenge is that the arrow cpp package doesn't use the CUDA Toolkit or CUDA Compiler. It only uses the CUDA Driver library.

> The challenge with `__cuda` is it doesn't really provide such a knob. Yes there is [`CONDA_OVERRIDE_CUDA`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html?highlight=CONDA_OVERRIDE_CUDA#overriding-detected-packages), but it doesn't really solve the problem. Other recipes or environment files can't constrain `__cuda`/`CONDA_OVERRIDE_CUDA`. It also may not always be obvious that `CONDA_OVERRIDE_CUDA` is set somewhere and affecting a Conda solve in the way that another package might
> 
> If I can suggest something, it would be using `cuda-version` for specifying the minimum CUDA version built with and adding `__cuda` only to require a GPU (similar to how OS-specific `noarch` packages have approached [conda-forge/ipykernel-feedstock#127](https://github.com/conda-forge/ipykernel-feedstock/pull/127) )

I would be fine with using the existence of `__cuda` and version of `cuda-version`, but that still has the same problems with `CONDA_OVERRIDE_CUDA` as far as I'm aware?

**Comment by jakirkham** [comment]
Could you please share more about what problems you see here? What still needs to be done?

**Comment by kkraus14** [comment]
That if someone has `CONDA_OVERRIDE_CUDA` defined for a different reason they'll still get the `__cuda` virtual package and the solver will allow installing a CUDA variant of the `libarrow` package.

The difference between
```
- __cuda >=9
```

and

```
- __cuda >0
- cuda-version >=9
```

Is that the latter unnecessarily enforces a cuda toolkit and libraries constraint where it doesn't need to.

**Comment by h-vetinari** [comment]
> the latter unnecessarily enforces a cuda toolkit and libraries constraint where it doesn't need to.

FWIW, I'm completely fine with dropping support for CUDA 8 and below.

**Comment by h-vetinari** [comment]
> FWIW, I'm completely fine with dropping support for CUDA 8 and below.

That said, it seems to me from re-reading the discussion that we can completely side-step `cuda-version` here, and just run-depend on `__cuda >=9` for the CUDA builds? WDYT @kkraus14
