### ISSUE TITLE
Arrow: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/arrow-cpp-feedstock#974]
Depends on the new CUDA packages ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by h-vetinari** [comment]
Cool! Are cross-compilation capabilities (already) on the radar for CUDA 12?

Arrow 8 & 9 have CUDA builds for aarch, but Arrow 10 & 11 have dropped them because of how the builds were restructured made it impossible to compile within the 6h timelimit. Would be really good to re-enable those also for CUDA 11, c.f. https://github.com/conda-forge/nvcc-feedstock/issues/95

**Comment by jakirkham** [comment]
FWIW this is mainly for tracking purposes atm. That said, we can collect any Arrow specific things we need to do for CUDA 12 here

Yes! We are working on cross-compilation support with CUDA 12. It is much needed for various reasons

Thanks for the context. Yeah cross-compilation will be a better way to handle these other architectures

Sorry I've not had much time to look outside this CUDA 12 project. It already requires a good amount of attention

There has been discussion about backfilling this package structure for CUDA 11 versions. Though that needs to be done more carefully to avoid accidental breakage. That would be one way to handle cross-compilation ( and possibly also collapse the CUDA 11 matrix further using `cuda-compat`: https://github.com/conda-forge/staged-recipes/issues/21382#issuecomment-1332593264 & https://github.com/conda-forge/staged-recipes/pull/21952 )

**Comment by h-vetinari** [comment]
Thanks for the info! From what I had gathered in the context of https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/210/ that you had discussed some next steps with @isuruf already, but it's possible I misinterpreted something. At the time I thought that PR would be all that's necessary, but that was incorrect.

**Comment by jakirkham** [comment]
Submitted PRs to backport these changes to the respective version branches that appear to still be supported:

* https://github.com/conda-forge/arrow-cpp-feedstock/pull/1083
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/1084
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/1085
